import { Link, useOutletContext } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { DashboardStats } from "../../components/DashboardStats";
import { WhatIfPanel } from "../../components/WhatIfPanel";

function QuickFacts({ data }) {
  const items = [
    { label: "Live data", sub: "FRED + market feeds" },
    { label: "Walk-forward validated", sub: "No lookahead bias" },
    { label: `${data.riskAlerts.length} shock alerts`, sub: "Statistical anomaly, not ML" },
  ];

  return (
    <div className="rounded-[4px] bg-[var(--color-ink-900)] p-5 text-white">
      <p className="eyebrow mb-1 !text-white/40">Pipeline</p>
      <p className="font-display mb-5 text-xl font-semibold">Fetch → Correlate → Forecast → Signal</p>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {items.map((item) => (
          <div key={item.label} className="rounded-[4px] bg-white/5 p-3.5">
            <p className="text-[13px] font-semibold text-white">{item.label}</p>
            <p className="mt-0.5 text-[11px] text-white/50">{item.sub}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

const JUMP_LINKS = [
  { to: "/dashboard/aluminium", label: "Aluminium forecast", sub: "6-month Ridge forecast + procurement signal" },
  { to: "/dashboard/pvc", label: "PVC resin forecast", sub: "6-month Ridge forecast + procurement signal" },
  { to: "/dashboard/graph", label: "Causal driver graph", sub: "Real correlations, feature justification" },
  { to: "/dashboard/risk", label: "Risk / shock alerts", sub: "COVID validation example" },
];

function JumpCard({ to, label, sub }) {
  return (
    <Link
      to={to}
      className="group flex items-center justify-between rounded-[4px] border border-[var(--color-hairline)] bg-white p-5 no-underline shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"
    >
      <div>
        <p className="text-[14px] font-semibold text-[var(--color-ink-primary)]">{label}</p>
        <p className="mt-1 text-[12px] text-[var(--color-ink-muted)]">{sub}</p>
      </div>
      <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--color-page)] transition-colors group-hover:bg-[var(--color-ink-900)]">
        <ArrowRight size={14} className="text-[var(--color-ink-secondary)] group-hover:text-white" />
      </span>
    </Link>
  );
}

export default function OverviewPage() {
  const { data, crudePct, fxPct, setCrudePct, setFxPct } = useOutletContext();

  return (
    <div className="space-y-6 pb-16">
      <div className="mb-1">
        <p className="eyebrow mb-1">Raw Material Intelligence</p>
        <h1 className="font-display text-3xl font-semibold tracking-tight text-[var(--color-ink-primary)]">
          Aluminium &amp; PVC Resin Forecast
        </h1>
        <p className="mt-1.5 max-w-2xl text-[13px] text-[var(--color-ink-muted)]">
          6-month Ridge forecast, causal driver graph, and procurement signals — data as of{" "}
          <span className="tabular-nums font-medium text-[var(--color-ink-primary)]">{data.dataAsOf}</span>
        </p>
      </div>

      <DashboardStats data={data} />

      <QuickFacts data={data} />

      <WhatIfPanel crudePct={crudePct} fxPct={fxPct} onCrudeChange={setCrudePct} onFxChange={setFxPct} />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        {JUMP_LINKS.map((link) => (
          <JumpCard key={link.to} {...link} />
        ))}
      </div>

      <footer className="pt-2 text-[11px] text-[var(--color-ink-muted)]">
        Static demo — reads only from data.json, generated by{" "}
        <code className="rounded bg-white px-1.5 py-0.5 ring-1 ring-[var(--color-hairline)]">
          python src/export_dashboard_data.py
        </code>
        . No live API calls from the browser.
      </footer>
    </div>
  );
}
