import { useEffect, useState } from "react";

// Reads the single static data.json - no backend, no live calls. Generated by
// python src/export_dashboard_data.py from the pipeline's saved outputs.
export function useDashboardData() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch("/data.json")
      .then((res) => {
        if (!res.ok) throw new Error(`data.json responded with ${res.status}`);
        return res.json();
      })
      .then(setData)
      .catch((err) => setError(err.message));
  }, []);

  return { data, error };
}
